[tool.poetry]
name = "mmlib"
version = "0.1.0"
description = "Library for MacMahon Tournaments"
authors = ["Oleksandr Hiliazov <oleksandr.hiliazov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
networkx = "^3.0"
pytest = "^7.4.3"
pre-commit = "^3.5.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
